version: '3.3'


services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short_url
    networks:
      local:
        aliases:
          - database

    restart: on-failure

    healthcheck:
      test: pg_isready -U postgres -d short_url
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate

    restart: on-failure

    depends_on:
      - postgresql

    volumes:
      - ./migrate:/database

    networks:
      - local

    command:
      [ "-database",  "postgres://postgres:postgres@database:5432/short_url?sslmode=disable" , "-path", "/database", "up" ]


  app:
    depends_on:
      - postgresql
      - migrate

    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_IP=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=short_url
    networks:
      - local
    restart: on-failure

networks:
  local:
    driver: bridge