version: '3.3'


services:

  redis:
    restart: on-failure

    image: "redis:latest"

    command: redis-server --port 6380 --requirepass password

    ports:
      - "6380:6380"

    environment:
      REDIS_REPLICATION_MODE: master

    networks:
      - local

  app:
    depends_on:
      - redis

    build: .

    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6380
      - REDIS_DB=0
      - REDIS_PASSWORD=password
    networks:
      - local

    restart: on-failure

networks:
  local:
    driver: bridge