[Postgres]
User = "server"
Pass = "M5F3wWtFxkQ8Ra4n"
DBName = "jwt_example"
IP = "127.0.0.1"
Port = 5432
Protocol = "tcp"

[Host]
Addr="0.0.0.0"
Port = 8080
Key = "cert/localhost.key"
Cert = "cert/localhost.crt"